// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package com.example.Data;

public final class DataTrackingClass {
  private DataTrackingClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataTracking_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataTracking_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndata.proto\"l\n\014DataTracking\022\017\n\007version\030" +
      "\001 \002(\t\022\014\n\004name\030\002 \002(\t\022\021\n\ttimestamp\030\003 \002(\006\022\020" +
      "\n\010phone_id\030\004 \001(\t\022\013\n\003lon\030\005 \001(\006\022\013\n\003lat\030\006 \001" +
      "(\006B\'\n\020com.example.DataB\021DataTrackingClas" +
      "sP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DataTracking_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DataTracking_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataTracking_descriptor,
        new java.lang.String[] { "Version", "Name", "Timestamp", "PhoneId", "Lon", "Lat", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
