/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package src.main.java;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Gender { 
  FEMALE, MALE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Gender\",\"namespace\":\"src.main.java\",\"symbols\":[\"FEMALE\",\"MALE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
